name: Deploy Wallet Bot

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            cd /home/runexei/runexei-bot/wallet_bot_project
            git pull origin main
            source .venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl restart runexei-bot.service
            sudo systemctl status runexei-bot.service --no-pager
